fix(mount_nas): check subpath

diff --git a/unclassified/bin/mount_nas b/unclassified/bin/mount_nas
--- a/unclassified/bin/mount_nas
+++ b/unclassified/bin/mount_nas
@@ -5,6 +5,10 @@ read -p "Enter username: " username
 read -s -p "Enter password: " password
 echo
 
+if [ -z "$subpath" ]; then
+    echo "Aborting: empty subpath."
+    exit 1
+fi
 if [ -z "$username" ]; then
     echo "Aborting: empty username."
     exit 1
